### ISSUE TITLE
Can't get past login

### ISSUE THREAD

**Issue by The-Chairman** [AppVet/appvet#12]
Sorry if this is not appropriate for this venue. 

I've been in the process of spinning up a copy of AppVet. I currently can't get past the login screen. It displays the text "Retrieving Data" and hangs. In the AppVet log, I see it complaining about the report templates being null. I am a bit confused because I have my env set up so that is has the path to the appvet_files directory and they should be accessible to Tomcat. I am not sure if this is causing my symptoms. Below is the relevant section of my log:

2016-11-28 02:23:34.688-0500 gov.nist.appvet.gwt.server.GWTServiceImpl:authenticateNonSSO line 205
[APPVET DEBUG] User 'mogata' authenticated
2016-11-28 02:23:34.786-0500 gov.nist.appvet.gwt.server.GWTServiceImpl:authenticateNonSSO line 211
[APPVET DEBUG] Updated client IP '127.0.0.1' for user 'mogata' updated.
2016-11-28 02:23:34.869-0500 gov.nist.appvet.gwt.server.GWTServiceImpl:authenticateNonSSO line 219
[APPVET DEBUG] Updated logon time for user 'mogata'.
2016-11-28 02:23:34.869-0500 gov.nist.appvet.gwt.server.GWTServiceImpl:authenticateNonSSO line 225
[APPVET DEBUG] mogata logged into GWT from: 127.0.0.1
2016-11-28 02:23:35.583-0500
gov.nist.appvet.gwt.server.GWTServiceImpl:getAllTools line 326
gov.nist.appvet.gwt.server.GWTServiceImpl:getConfigInfo line 285
gov.nist.appvet.gwt.server.GWTServiceImpl:authenticateNonSSO line 238
[APPVET ERROR] Report template for audit is null!
2016-11-28 02:23:35.584-0500
gov.nist.appvet.gwt.server.GWTServiceImpl:getAllTools line 326
gov.nist.appvet.gwt.server.GWTServiceImpl:getConfigInfo line 285
gov.nist.appvet.gwt.server.GWTServiceImpl:authenticateNonSSO line 238
[APPVET ERROR] Report template for approval is null!
2016-11-28 02:23:35.584-0500
gov.nist.appvet.gwt.server.GWTServiceImpl:getAllTools line 326
gov.nist.appvet.gwt.server.GWTServiceImpl:getConfigInfo line 285
gov.nist.appvet.gwt.server.GWTServiceImpl:authenticateNonSSO line 238
[APPVET ERROR] Report template for androidsummary is null!
2016-11-28 02:23:35.585-0500
gov.nist.appvet.gwt.server.GWTServiceImpl:getAllTools line 326
gov.nist.appvet.gwt.server.GWTServiceImpl:getConfigInfo line 285
gov.nist.appvet.gwt.server.GWTServiceImpl:authenticateNonSSO line 238
[APPVET ERROR] Report template for golive is null!

**Comment by aglynn** [comment]
@The-Chairman - Can you please open the browser debugger tools and go to the page, open the network settings, and take a screenshot of what request and response is (as well as the rest of the browser so that I can gage who is showing up exactly)? There is an HTTP request going on in the background that isn't working and the response may provide a clue about what is the problem. The "report template is null!" error I think is not the cause of the problem.

**Comment by The-Chairman** [comment]
Sorry for the delay in my response. End of the year and such.  Attached is the requested screenshot.
![appvet-browser-network-screenshot](https://cloud.githubusercontent.com/assets/24219698/21317680/2b1fb0dc-c5d4-11e6-9525-682e0f0d249d.png)

**Comment by aglynn** [comment]
It looks like a javascript error. It might ultimately go back to a server
side error because of how tightly GWT ties the front and back end, but
let's try seeing if it is front end javascript specific. Can you please now
try to clear all the browser cache, close the browser, reopen it, and come
back to this page and try it again?

**Comment by The-Chairman** [comment]
It looks like I am seeing the same behavior
![screen shot 2016-12-23 at 10 11 12 am](https://cloud.githubusercontent.com/assets/24219698/21456728/366d09cc-c8f8-11e6-8af9-bea78f8dce3b.png)

**Comment by aglynn** [comment]
@AppVet or @StephenQuirolgico - Do you have any ideas? 

@The-Chairman - Maybe you can start over and try to install the most recent version of AppVet. Please make sure that your webserver set up is good: For example, I believe you will want to pointing to a Java 8 installation. What webserver are you using and what version is it? What OS and version are you on? What Java version are you currently pointing to?

**Comment by AppVet** [comment]
@The-Chairman - The bug you are experiencing has been fixed in the just-released v2.4.7 (see [https://github.com/AppVet/appvet/releases/tag/v2.4.7](url)). To ensure correct installation, it will be necessary for you to first log into your MySQL and run `DROP DATABASE appvet;` followed by `DROP DATABASE appvet;` to reset the appvet database. Then, you will need to follow the Installation directions in the newly-updated documentation (see [http://appvet.github.io/appvet/](url)). Please let us know if you have any additional problems.

**Comment by The-Chairman** [comment]
The update did the trick! Thanks for sticking with this thread despite me taking so long to get back to you!
