### ISSUE TITLE
Client API returning 500 status code

### ISSUE THREAD

**Issue by The-Chairman** [AppVet/appvet#13]
I am tooling around with the client API with a simple python script. Instead of getting the expected 200/400 response codes. I get a 500 response code. I am running AppVet out of a terminal and see this message printed to stdout:

authHeaderValue is bW9nYXRhOm1saTY5OQ==

Checking the access log, I see this corresponding log entry:

127.0.0.1 - - [16/Jan/2017:15:19:48 -0500] "GET /appvet/AppVetServlet HTTP/1.1" 500 1603

Below is the python code I am using to test this out. I get similar results when I use wget. Is there a configuration setting I need to enable before this feature works? 

Thanks!

import requests
from base64 import b64encode

user_pass = b64encode(b"totallynotmyusername:totallynotmypassword").decode("ascii")

resp = requests.get('http://127.0.0.1:8080/appvet/AppVetServlet',
  headers={"Authorization":user_pass } )

print( resp.status_code )

**Comment by AppVet** [comment]
Can you a look at your /appvet_files/logs/appvet_log.txt file and post the entries in the log where the HTTP 500 is returned for the query? Note that the client API documentation is still in the works but will hopefully be up soon.

**Comment by AppVet** [comment]
The fix for this bug is now included in the AppVet v2.4.8 release (See https://github.com/AppVet/appvet/releases/tag/v2.4.8). In addition, the Client API documentation has been updated on http://appvet.github.io/appvet/ (select Client API link) which includes a link to an example API tester, 'AppVetClientAPITester.java', that is now included in 2.4.8.

**Comment by The-Chairman** [comment]
I deployed the war for version 2.4.8. Afterwards I couldn't load Appvet. Navigating to the url just displayed a blank screen.  I think it is missing the javascript files that should be packed along within it. Checking the logs I was seeing a lot of 404 errors for missing js files. I unpacked the appvet subdirectory from 2.4.7 and moved it into my webapps directory and that fixed the UI.

I still get the 500 response from the server when I attempt to use the API.

**Comment by AppVet** [comment]
My apologies, for some reason 2.4.8 did not include the js files. I have regenerated the war file and added it to release 2.4.9 (see https://github.com/AppVet/appvet/releases/tag/v2.4.9). I recommend using 2.4.9 since the files in 2.4.7 that you copied contains a number of bugs which you still might be experiencing. After installing the 2.4.9 war file in your Tomcat /webapps directory, it is recommended to clear your browser cache before starting Tomcat. If you still experience the HTTP 500 responses, let me know the OS (and version), browser (and version) you are using, and if you could also send me the log file (/appvet_files/logs/appvet_log.txt) I will try to pinpoint the problem.

**Comment by AppVet** [comment]
Ok, I found the problem. In your python script, you need to add the string "Basic " (with a space) before the base64 encoding used in the Authorization header: ```headers={"Authorization":"Basic " + user_pass } ```

After this, I was able to get a non-500 HTTP code.

**Comment by AppVet** [comment]
I will add some code that returns a more descriptive error message.

**Comment by The-Chairman** [comment]
Thank you for the help! That cleared things up for me. I apologize for the error in my code. I was able to successfully receive a session idea from the API!
